function k(b,a,c,d){b.s.lb(b.ob,a,c,d)}function l(b,a,c,d){b.s.ca?k(b,a,c,d):b.s.Ge()._OnMessageFromDOM({type:"event",component:b.ob,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.s.C(b.ob,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Tb||(b.s.rd(b.Yd),b.Tb=!0)}window.Na=class{constructor(b,a){this.s=b;this.ob=a;this.Tb=!1;this.Yd=()=>this.Qa()}hd(){}Qa(){}};
window.qf=class{constructor(){this.dd=-1}j(){-1!==this.dd&&(self.clearTimeout(this.dd),this.dd=-1)}};"use strict";class aa{constructor(b){this.Lc=b;this.Oc=!1;this.Vc=!0}}function ba(b,a){const c=a.elementId,d=b.md(c,a),e=new aa(d);b.rb.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Vc=!!a.isVisible;d.addEventListener("focus",()=>{ca(b,"elem-focused",c)});d.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});b.Pb&&document.body.appendChild(d)}
function da(b,a){n(b,"get-element",c=>{const d=v(b,c.elementId);return a(d,c)})}function v(b,a){b=b.rb.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Lc}function ca(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.re=class extends self.Na{constructor(b){super(b,"progress-bar");this.rb=new Map;this.Pb=!0;t(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=v(this,a);this.Pb&&c.parentElement.removeChild(c);this.rb.delete(a)}],["set-visible",a=>{if(this.Pb){var c=this.rb.get(a.elementId),d=c.Lc;c.Oc?d.style.display=a.isVisible?"":"none":c.Vc=!!a.isVisible}}],["update-position",a=>{if(this.Pb){var c=this.rb.get(a.elementId),d=c.Lc;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";a=a.fontSize;null!==a&&(d.style.fontSize=a+"em");c.Oc||(c.Oc=!0,c.Vc&&(d.style.display=""))}}],["update-state",a=>{const c=v(this,a.elementId);this.wc(c,a)}],["focus",a=>this.Fc(a)],["set-css-style",a=>{const c=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);da(this,a=>
a)}md(){throw Error("required override");}wc(){throw Error("required override");}Fc(b){var a=v(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.ef?new Promise(c=>{const d="c3_resolve_"+ha;++ha;self[d]=c;a.textContent=b.jf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ia=!1,ja=!1;function ka(){if(!ia){try{new Worker("blob://",{get type(){ja=!0}})}catch(b){}ia=!0}return ja}let z=new Audio;
const la={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;async function oa(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,ra=new Map;let sa=0;const ta=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ta.push(b)};const ua=new Set(["cordova","playable-ad","instant-games"]);let va=!1;
window.pa=class b{constructor(a){this.ca=a.lf;this.ya=null;this.ba="";this.cb=a.hf;this.Fb={};this.Wa=this.va=null;this.Rb=[];this.J=this.na=null;this.Sc=!1;this.Fd=0;this.ub=null;this.bb=-1;this.af=()=>this.Oe();this.ab=[];this.ed=null;this.Zd=[];this.v=a.$d;this.Ub="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ka()||(this.ca=!1);this.ca&&fa&&(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===
this.v&&this.ca)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.wa()?self.chrome.webview.addEventListener("message",c=>this.wd(c.data)):"macos-wkwebview"===this.v&&(self.C3WrapperOnMessage=c=>this.wd(c));this.Xb=this.sa=null;"html5"!==this.v||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Ke(c));this.C("runtime","create-job-worker",()=>this.Le());this.C("runtime","send-wrapper-extension-message",c=>this.Re(c));"cordova"===this.v?document.addEventListener("deviceready",()=>this.ud(a)):this.ud(a)}j(){this.xc();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Wa&&(this.Wa.j(),this.Wa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}ve(){return ea&&"cordova"===this.v}sc(){const a=
navigator.userAgent;return ea&&ua.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}te(){return w}od(){return w&&ua.has(this.v)}wa(){return"windows-webview2"===this.v||!!("preview"===this.v&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async ud(a){"macos-wkwebview"===this.v?this.Ea({type:"ready"}):this.wa()&&(this.Ue(),this.Zd=(await this.Je()).registeredComponentIds);if("playable-ad"===this.v){this.sa=self.c3_base64files;this.Xb={};await this.Ce();
for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.Xb.hasOwnProperty(c)?a.fb[d]={ef:!0,jf:this.Xb[c]}:this.sa.hasOwnProperty(c)&&(a.fb[d]=URL.createObjectURL(this.sa[c]))}a.lc=[]}if("nwjs"===this.v&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.rd(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.gf?this.ba=a.gf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.nf&&(this.Fb=a.nf);
c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ne(d));this.ub=new self.we(this);await wa(this.ub);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ie(a,c.port2):
await this.He(a,c.port2)}zc(a){a=this.Fb.hasOwnProperty(a)?this.Fb[a]:a.endsWith("/workermain.js")&&this.Fb.hasOwnProperty("workermain.js")?this.Fb["workermain.js"]:"playable-ad"===this.v&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async nc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.v&&this.Ub)return a=await this.Gb(d.df?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}td(a){var c=this.ba,d=location.href,e=this.qa(),f=this.ia(),g=window.devicePixelRatio,h=b.jb(),m=a.uf,p=window.cr_previewImageBlobs||this.sa,q=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.cr_swClientId||
"";a=a.$d;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.ub;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.tf,jobScheduler:{inputPort:B.Rc,outputPort:B.Zc,maxNumWorkers:B.Ye},supportedAudioFormats:la,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.cb+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.ve(),isiOSWebView:this.sc(),isWebView2Wrapper:this.wa(),wrapperComponentIds:this.Zd,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ie(a,c){const d=this.zc(a.mf);"preview"===this.v?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const p=q=>{this.va.removeEventListener("message",p);q.data&&"ok"===q.data.type?h():m()};this.va.addEventListener("message",p);this.va.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.va=await this.nc(d,this.ba,{type:"module",name:"Runtime",df:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.lc||[],g=a.fb;f=await Promise.all(f.map(h=>this.Ra(h)));g=await Promise.all(g.map(h=>this.Ra(h)));if("cordova"===this.v)for(let h=0,m=a.kc.length;h<
m;++h){const p=a.kc[h],q=p[0];if(q===a.fd||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.Ra(q)}this.va.postMessage(Object.assign(this.td(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.kc,mainProjectScript:a.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...xa(this.ub)]);this.Rb=F.map(h=>new h(this));this.sd();ya(this.na);self.c3_callFunction=(h,m)=>{var p=this.na;return p.s.qd(p.ob,
"js-invoke-function",{name:h,params:m})};"preview"===this.v&&(self.goToLastErrorScript=()=>this.lb("runtime","go-to-last-error-script"))}async He(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=F.map(g=>new g(this));this.sd();var d=a.fb.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.lc)){var e=[...a.lc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ra(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.fd;const f=a.kc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ra(h),await y(h),"preview"!==this.v||d[g]||this.xd(g,"main script did not run to completion")}catch(m){this.xd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ra(h),await y(h);"preview"===this.v&&"object"!==typeof self.pf.rf?
(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.td(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:ta}),ya(this.na),this.vd(),this.Wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Wa,a))}xd(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}vd(){this.Lb()}Lb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Le(){const a=await za(this.ub);return{outputPort:a,transferables:[a]}}Ge(){if(this.ca)throw Error("not available in worker mode");return this.Wa}lb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}qd(a,c,d,e,f){const g=sa++,h=new Promise((m,p)=>{ra.set(g,{resolve:m,reject:p})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Me(a);if("result"===c)this.Pe(a);else if("runtime-ready"===c)this.Qe();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.vd();else throw Error(`unknown message '${c}'`);
}Me(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Pe(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ra.get(c);d?e.resolve(a):e.reject(a);ra.delete(c)}C(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ma(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}sd(){for(const a of this.Rb)if("runtime"===a.ob){this.na=a;
return}throw Error("cannot find runtime DOM handler");}Ne(a){this.lb("debugger","message",a)}Qe(){for(const a of this.Rb)a.hd()}static jb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||va)}static Mb(a){va=!!a}rd(a){this.ab.push(a);this.Hc()}Te(a){a=this.ab.indexOf(a);if(-1===a)throw Error("invalid callback");this.ab.splice(a,1);this.ab.length||this.xc()}Hc(){-1===this.bb&&this.ab.length&&(this.bb=requestAnimationFrame(this.af))}xc(){-1!==this.bb&&
(cancelAnimationFrame(this.bb),this.bb=-1)}Oe(){this.bb=-1;for(const a of this.ab)a();this.Hc()}Da(a){this.na.Da(a)}Pa(a){this.na.Pa(a)}Gc(){this.na.Gc()}Jb(a){this.na.Jb(a)}ue(){return!!la["audio/webm; codecs=opus"]}async Ve(a){a=await this.qd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ye(a){this.Sc=!0;this.Fd=a}se(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}pd(a){return!this.se(a)}async Ra(a){return"cordova"===this.v&&
(a.startsWith("file:")||this.Ub&&this.pd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ke(a){const c=a.filename;switch(a.as){case "text":return await this.qe(c);case "buffer":return await this.Gb(c);default:throw Error("unsupported type");}}ld(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async qe(a){a=
await this.ld(a);return await oa(a)}yc(){if(C.length&&!(8<=E)){E++;var a=C.shift();this.De(a.filename,a.kf,a.cf)}}Gb(a){return new Promise((c,d)=>{C.push({filename:a,kf:e=>{E--;this.yc();c(e)},cf:e=>{E--;this.yc();d(e)}});this.yc()})}async De(a,c,d){try{const e=await this.ld(a),f=await qa(e);c(f)}catch(e){d(e)}}wd(a){if("entered-fullscreen"===a)b.Mb(!0),H(this.na);else if("exited-fullscreen"===a)b.Mb(!1),H(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ed(a),
this.ed=null):"extension-message"===c?this.lb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Re(a){this.Ea({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ea(a){this.wa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.v&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Ue(){window.moveTo=(a,c)=>
{this.Ea({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ea({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Je(){return this.wa()?new Promise(a=>{this.ed=a;this.Ea({type:"wrapper-init"})}):Promise.resolve()}async Ce(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Be(c,d));await Promise.all(a)}async Be(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.Xb[a]=c.str;else{let d=
await this.Fe(c);d||(d=this.Ee(c));this.sa[a]=d}}async Fe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ee(a){a=this.Se(a);return this.Ae(a.data,a.ff)}Se(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{ff:a,data:d}}Ae(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const I=self.pa;
function Aa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Ba=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),J={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ca={dispatchUserScriptEvent:!0},Da={dispatchRuntimeEvent:!0};
function Ea(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Fa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await Fa(b)}finally{URL.revokeObjectURL(b)}}
function Ga(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ha(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await Ga(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function Ia(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ja=new Set(["input","textarea","datalist","select"]),Ka=new Set(["canvas","body","html"]);function L(b){b.target.tagName&&Ka.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function La(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ha(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ma=!1;document.addEventListener("pause",()=>Ma=!0);document.addEventListener("resume",()=>Ma=!1);function ya(b){b.Ed=!0;b.Wc=b.s.qa();b.vb=b.s.ia()}function H(b){if(!b.$){var a=I.jb();a&&"any"!==b.bd&&Oa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ia()})}}async function Pa(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Qa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ra(b){return await self.C3_GetSvgImageSize(b.blob)}function Sa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ta(b){self.setTimeout(()=>{b.Dd=!0},1E3);"cordova"===b.s.v?(document.addEventListener("pause",()=>Ua(b,!0)),document.addEventListener("resume",()=>Ua(b,!1))):document.addEventListener("visibilitychange",()=>Ua(b,"hidden"===document.visibilityState));b.ac=!("hidden"!==document.visibilityState&&!Ma);return{isSuspended:b.ac}}
function Va(b){b.zd||(b.zd=!0,window.addEventListener("deviceorientation",a=>{b.$||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},J)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},J)}))}
function Wa(b){b.yd||(b.yd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},J)}}))}async function Xa(b){await Ea(b.url)}
function Ya(b,a){b.Gd=a.message;-1===b.Mc&&(b.Mc=setTimeout(()=>{b.Mc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Gd)},250))}function Za(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:I.jb(),innerWidth:b.qa(),innerHeight:b.ia()})}function Ua(b,a){b.ac!==a&&((b.ac=a)?b.s.xc():b.s.Hc(),k(b,"visibilitychange",{hidden:a}))}
function $a(b,a,c){"Backspace"===c.key&&L(c);if(!b.$){var d=Ba.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},J)}}function ab(b,a,c,d){b.$||Aa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function bb(b){window!==window.top&&window.focus();cb(b.target)&&document.activeElement&&!cb(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.Ab);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},J);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),ab(b,d,c,Ca),b.Ab=c.buttons)}}
function db(b,a,c){if(!b.$&&!Aa(c)){var d=b.Ab;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},J);b.Ab=c.buttons;ab(b,c.type,c,Ca)}}
function N(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
J)}}function eb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function fb(b,a,c,d){const e=b.qa(),f=b.ia();b.eb=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.jb()}):10>d&&hb(b,e,f,d+1)}
function hb(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>fb(b,a,c,d),48)}
function Oa(b){b=b.bd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function cb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
I.Ma(class extends self.Na{constructor(b){super(b,"runtime");this.Ld=!0;this.Ed=!1;this.eb=-1;this.bd="any";this.ac=this.yd=this.zd=!1;this.hc=document.createElement("div");this.hc.className="c3-screen-reader-text";this.hc.setAttribute("aria-live","polite");document.body.appendChild(this.hc);this.Ha=null;this.$=!1;this.Gd="";this.Mc=-1;this.Dd=!1;this.Wc=b.qa();this.vb=b.ia();this.da=this.Eb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Sc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Ld&&(e.style.display="",this.Ld=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Pa(d));b.C("runtime","raster-svg-image",d=>Qa(d));b.C("runtime",
"get-svg-image-size",d=>Ra(d));b.C("runtime","set-target-orientation",d=>{this.bd=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Sa(d));b.C("runtime","go-to-script",d=>Sa(d));b.C("runtime","before-start-ticking",()=>Ta(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ha||(this.Ha=document.createElement("div"),this.Ha.id="inspectOutline",document.body.appendChild(this.Ha));var e=this.Ha;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ha&&(this.Ha.style.display="none")});b.C("runtime","enable-device-orientation",()=>Va(this));b.C("runtime","enable-device-motion",()=>Wa(this));b.C("runtime","add-stylesheet",d=>Xa(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>this.Cc(d));
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.hc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.ye(d.duration)});b.C("runtime","export-to-video-progress",d=>Ya(this,d));b.C("runtime","exported-to-video",d=>{window.bf({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.bf({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ia(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",
L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.Ab=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",La,{passive:!1});window.addEventListener("wheel",La,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Ed){var d=this.qa();var e=this.ia();if(this.s.od()){if(this.Dd){if(this.Wc===
d&&e<this.vb){this.Eb=this.vb-e;eb(this,this.vb,this.Eb);d=void 0;break a}0<this.Eb&&(this.Eb=0,eb(this,e,this.Eb))}this.Wc=d;this.vb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:I.jb()});this.s.sc()&&(-1!==this.eb&&clearTimeout(this.eb),fb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>H(this));window.addEventListener("webkitfullscreenchange",()=>H(this));window.addEventListener("mozfullscreenchange",()=>
H(this));window.addEventListener("fullscreenerror",d=>Za(this,d));window.addEventListener("webkitfullscreenerror",d=>Za(this,d));window.addEventListener("mozfullscreenerror",d=>Za(this,d));if(b.sc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ia(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Xa=new Set;this.Zb=new WeakSet;this.xa=!1}hd(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Da)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},Da);this.Ab=0});window.addEventListener("focusin",a=>{a=a.target;(Ja.has(a.tagName.toLowerCase())||Ia(a))&&
k(this,"keyboard-blur",null,Da)});window.addEventListener("keydown",a=>$a(this,"keydown",a));window.addEventListener("keyup",a=>$a(this,"keyup",a));window.addEventListener("dblclick",a=>ab(this,"dblclick",a,J));window.addEventListener("wheel",a=>{this.$||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},J)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{bb(a);M(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{M(this,"pointermove",a)}):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{bb(a);db(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>db(this,
"pointermove",a)),window.addEventListener("mouseup",a=>db(this,"pointerup",a)),window.addEventListener("touchstart",a=>{bb(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Gc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.te()&&!this.s.od()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{eb(this,this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.s.qa()}ia(){return this.s.ia()}Gc(){var b=[...this.Xa];this.Xa.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Zb.has(a)||this.Xa.add(a)})}Da(b){if("function"!==typeof b.play)throw Error("missing play function");
this.Zb.delete(b);let a;try{a=b.play()}catch(c){this.Xa.add(b);return}a&&a.catch(()=>{this.Zb.has(b)||this.Xa.add(b)})}Pa(b){this.Xa.delete(b);this.Zb.add(b)}Jb(b){this.xa=!!b}Cc(b){alert(b.message)}});"use strict";
async function wa(b){if(b.We)throw Error("already initialised");b.We=!0;var a=b.za.zc(("playable-ad"===b.za.v?b.za.cb:"")+"dispatchworker.js");b.Kc=await b.za.nc(a,b.nb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Zc=await za(b)}function xa(b){return[b.Rc,b.Zc]}
async function za(b){const a=b.Md.length;var c=b.za.zc(("playable-ad"===b.za.v?b.za.cb:"")+"jobworker.js");c=await b.za.nc(c,b.nb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Md.push(c);return e.port1}
self.we=class{constructor(b){this.za=b;this.nb=b.ba;this.nb="preview"===b.v?this.nb+"workers/":this.nb+b.cb;this.Ye=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Md=[];this.Zc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.pa({lf:!0,mf:"workermain.js",fb:["scripts/c3runtime.js"],kc:[],fd:"",hf:"scripts/",lc:[],$d:"html5"}));"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.cd=a.timeScaleMode;b.Rd=["equalpower","HRTF","soundfield"][a.panningModel];b.Cd=["linear","inverse","exponential"][a.distanceModel];b.Sd=a.refDistance;b.Qd=a.maxDistance;b.Ud=a.rolloffFactor;if(b.s.Sc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Fd)});else{var c={latencyHint:a.latencyHint};b.Xd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ea);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Nd=g.slice(0);mb(b,g);try{b.R=await nb(b,c,d,e,g,f);if(q){P(b.R,!0);var r=b.R,B=q.innerAngle,ma=q.outerAngle,na=q.outerGain;if(r.tb){ob(r,q.x,q.y,q.z,q.angle);var D=self.gb.ze;r.ta[0]!==D(B)&&
(r.ta[0]=D(B),r.F.coneInnerAngle=D(B));r.ta[1]!==D(ma)&&(r.ta[1]=D(ma),r.F.coneOuterAngle=D(ma));r.ta[2]!==na&&(r.ta[2]=na,r.F.coneOuterGain=na)}q.hasOwnProperty("uid")&&(b.R.ra=q.uid)}else"number"===typeof A&&0!==A?(Q(b.R,!0),pb(b.R,A)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,m,p,x)}catch(Db){console.error("[Construct] Audio: error starting playback: ",Db);return}finally{c=g.join(" ");d=b.Cb.get(c);if(!d)throw Error("expected pending tag");d.gd--;0===d.gd&&(d.resolve(),b.Cb.delete(c))}u(b)}
async function qb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const h of R(b,c))if(!h.Va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.La=d;h.Ua=g;h.Wd=a}S(b)}async function sb(b,a){const c=a.tags;a=a.rate;await rb(b,c);for(const d of R(b,c))d.ma!==a&&(d.ma=a,d.Fa())}async function tb(b,a){const c=a.tags;a=a.pos;await rb(b,c);for(const d of R(b,c))d.tc(a)}
async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ka.indexOf(a),-1!==a&&b.ka.splice(a,1)}
async function wb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct] Audio: error loading convolution: ",m);return}for(const m of d){if("filter"===c)d=new self.fe(b,...e);else if("delay"===c)d=new self.de(b,...e);else if("convolution"===c){var g=d=new self.ce(b,f.ja,...e),h=a.bufferType;g.Ad=a.bufferOriginalUrl;g.Bd=h}else if("flanger"===c)d=new self.ge(b,...e);else if("phaser"===
c)d=new self.ie(b,...e);else if("gain"===c)d=new self.he(b,...e);else if("stereopan"===c)d=new self.ke(b,...e);else if("tremolo"===c)d=new self.le(b,...e);else if("ringmod"===c)d=new self.je(b,...e);else if("distortion"===c)d=new self.ee(b,...e);else if("compressor"===c)d=new self.be(b,...e);else if("analyser"===c)d=new self.ae(b,...e);else throw Error("invalid effect type");g=b;h=m;h=h.toLowerCase();let p=g.la.get(h);p||(p=[],g.la.set(h,p));d.Kd=p.length;d.ad=h;p.push(d);xb(g,h)}yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.la.values())for(const g of f)g.j();b.la.clear();b.ic=a.timeScale;b.Nc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ea[e]=d[e];b.g.listener.setOrientation(...b.ea)}b.xa=a.isSilent;b.s.Jb(b.xa);b.Yb=a.masterVolume;b.Ta.gain.value=
b.Yb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>wb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Ab(b,f,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Jd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.lb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Jd=!0);await c}catch(c){Cb(c)}}
function kb(b){b.Sb||(b.Qc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Sb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ka)if(g.ib()===c)return await Eb(g),g;if(f)return null;if(e&&(b.cc||b.Id)){f=0;for(let h=0,m=b.ka.length;h<m;++h)g=b.ka[h],b.ka[f]=g,g.Ba()?g.j():++f;b.ka.length=f}f="audio/webm; codecs=opus"===d&&!b.Xd;e&&f&&(b.Id=!0);c=!e||b.cc||f?new self.oe(b,a,c,d,e,f):new self.me(b,a,c,d,e);b.ka.push(c);await Eb(c);b.Pd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ha()}),b.Pd.add(a));return c}
function Fb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Gb(b,a){return(a=b.la.get(a.toLowerCase()))?a[0].N():b.ga()}function xb(b,a){a=a.toLowerCase();let c=b.ga();var d=b.la.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ga()):e.U(d[f+1].N())}}for(const f of Hb(b,a))d=c,e=f.fa||f.F||f.G,e.disconnect(),e.connect(d);b.Ia&&b.Xc===a&&(b.Ia.disconnect(),b.Ia.connect(c))}
function*Hb(b,a){if(a)for(const c of b.H)Fb(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Ib(b,a,c){return c?b.s.Ve(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Jb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Fb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function nb(b,a,c,d,e,f){for(const g of b.H)if(g.ib()===c&&(g.mc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Ic?new self.ne(a.u,a,e):new self.pe(a.u,a,e);b.H.push(e);return e}
function mb(b,a){a=a.join(" ");let c=b.Cb.get(a);if(!c){let d=null;c={gd:0,promise:new Promise(e=>d=e),resolve:d};b.Cb.set(a,c)}c.gd++}function rb(b,a){return(b=b.Cb.get((0===a.length?b.Nd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Sa.size)u(b);else for(const a of b.H)if(!a.I&&!a.O()){u(b);break}}function Kb(b,a,c,d){k(b,"trigger",{type:a,tags:c,aiid:d})}function yb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Lb(b)))}
function Lb(b){const a={};for(const [c,d]of b.la)a[c]=d.map(e=>e.hb());k(b,"fxstate",{fxstate:a});b.Tc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],f=d.orient,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],e.setPosition(...b.Za),e.setOrientation(...b.Ya),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),pb(b,d));c.Play(m,p,q,0);a.isPlaying||c.kb();c.Bc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.gb=class extends self.Na{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Sb=this.Qc=!1;this.Aa=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Qc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Sb=!1)}};this.ka=[];this.H=[];this.R=null;this.Nd=[];this.Pd=new Set;this.Od=-1;this.Cb=new Map;this.Yb=1;this.xa=!1;this.cd=0;this.ic=1;this.Nc=0;this.Rd="HRTF";this.Cd="inverse";this.Sd=600;this.Qd=1E4;this.Ud=1;this.aa=[0,0,0];this.ea=[0,0,-1,0,1,0];this.Id=this.cc=!1;this.Xd=this.s.ue();this.la=new Map;this.Sa=new Set;this.Jd=this.Tc=!1;this.Xc="";this.Ia=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ia&&this.Ia.disconnect();this.Xc=c.toLowerCase();this.Ia=this.g.createMediaStreamSource(a);
this.Ia.connect(Gb(this,this.Xc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Ta.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.kb():d.Ib();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.Yb=a.vol;this.Ta.gain.value=this.Yb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Mb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.s.Jb(this.xa);for(const c of this.H)c.Nb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.uc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ka)a.j();this.ka.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.vc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.la.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);yb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.la.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.la.delete(a);xb(this,a)}}],["tick",a=>{this.ic=a.timeScale;this.Nc=a.gameTime;this.Od=a.tickCount;if(0!==this.cd)for(var c of this.H)c.Fa();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ea[0]!==
c[0]||this.ea[1]!==c[1]||this.ea[2]!==c[2]||this.ea[3]!==c[3]||this.ea[4]!==c[4]||this.ea[5]!==c[5])){for(let d=0;6>d;++d)this.ea[d]=c[d];this.g.listener.setOrientation(...this.ea)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&ob(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ga(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ga()}Hb(){return this.xa}Da(b){this.s.Da(b)}Pa(b){this.s.Pa(b)}Qa(){for(var b of this.Sa)b.Qa();
b=this.g.currentTime;for(var a of this.H)a.Qa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.hb());k(this,"state",{tickCount:this.Od,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.ad,index:c.Kd,peak:c.$a,rms:c.Td,binCount:c.l.frequencyBinCount,freqBins:c.Hd}))});0===a.length&&0===this.Sa.size&&this.Tb&&(this.s.Te(this.Yd),this.Tb=!1)}static ze(b){return b*ib}static nd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static xe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Ma(self.gb);"use strict";function Eb(b){b.Wb||(b.Wb=b.Ac());return b.Wb}self.jd=class{constructor(b,a,c,d,e){this.u=b;this.$e=a;this.Ka=c;this.T=d;this.Xe=e;this.Ic="";this.Wb=null}j(){this.Wb=this.u=null}Ac(){}V(){return this.u.V()}pc(){return this.$e}ib(){return this.Ka}oc(){return this.T}Ba(){return this.Xe}ha(){}};"use strict";
self.me=class extends self.jd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Ic="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.wb=this.xb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Bb=this.V().createGain();this.zb=null;this.M.addEventListener("canplay",()=>{this.xb&&(this.xb(),this.wb=this.xb=null);!this.zb&&this.M&&(this.zb=this.V().createMediaElementSource(this.M),this.zb.connect(this.Bb))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ka}' error: `,f);this.wb&&(this.wb(f),this.wb=this.xb=null)})}j(){Jb(this.u,this);this.Bb.disconnect();this.Bb=null;this.zb.disconnect();this.zb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ac(){return new Promise((b,a)=>{this.xb=b;this.wb=a;this.M.src=this.Ka})}W(){return this.M}ha(){return this.M.duration}};"use strict";
async function Nb(b){if(b.Ga)return b.Ga;var a=b.u.s;if("cordova"===a.v&&a.pd(b.Ka)&&a.Ub)b.Ga=await a.Gb(b.Ka);else{a=await fetch(b.Ka);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ga=await a.arrayBuffer()}}async function Ob(b){if(b.ja)return b.ja;b.ja=await Ib(b.u,b.Ga,b.Ze);b.Ga=null}
self.oe=class extends self.jd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Ic="webaudio";this.ja=this.Ga=null;this.Ze=!!f}j(){Jb(this.u,this);this.ja=this.Ga=null;super.j()}async Ac(){try{await Nb(this),await Ob(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ka}': `,b)}}ha(){return this.ja?this.ja.duration:0}};"use strict";let Pb=0;
function P(b,a){a=!!a;b.tb!==a&&(b.tb=a,b.tb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Rd,b.F.distanceModel=b.u.Cd,b.F.refDistance=b.u.Sd,b.F.maxDistance=b.u.Qd,b.F.rolloffFactor=b.u.Ud),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ga())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ga())))}
function Q(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(P(b,!1),b.fa=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.fa),b.fa.connect(b.ga())):(b.fa.disconnect(),b.fa=null,b.G.disconnect(),b.G.connect(b.ga())))}function pb(b,a){b.Vb&&b.$c!==a&&(b.fa.pan.value=a,b.$c=a)}function T(b,a){b.La=a;b.G.gain.cancelScheduledValues(0);b.Ua=-1;b.G.gain.value=b.qc()}function Mb(b,a){a=!!a;b.Va!==a&&(b.Va=a,b.Nb())}
function ob(b,a,c,d,e){if(b.tb){var f=b.Za,g=b.Ya,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Uc?b.u.Nc:performance.now()/1E3}
self.kd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Ob=Pb++;this.G=this.V().createGain();this.G.connect(this.ga());this.F=null;this.tb=!1;this.Za=[0,0,0];this.Ya=[0,0,0];this.ta=[0,0,0];this.fa=null;this.Vb=!1;this.$c=0;this.I=!0;this.Y=this.ua=this.K=!1;this.La=1;this.Va=!1;this.ma=1;b=this.u.cd;this.Uc=1===b&&!this.Ba()||2===b;this.Ua=this.ra=-1;this.Wd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.fa&&(this.fa.disconnect(),this.fa=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ga(){return Gb(this.u,0<this.oa.length?this.oa[0]:"")}pc(){return this.P.pc()}ib(){return this.P.ib()}oc(){return this.P.oc()}Ba(){return this.P.Ba()}O(){}mc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Oa(){}ha(){return this.P.ha()}Play(){}Ca(){}kb(){}Ib(){}Qa(b){-1!==this.Ua&&b>=this.Ua&&(this.Ua=-1,this.Wd&&this.Ca(),Kb(this.u,"fade-ended",this.oa,this.Ob))}qc(){const b=this.La;return isFinite(b)?b:0}Hb(){return this.u.Hb()}Nb(){}uc(){}Fa(){}tc(){}vc(){}rc(){}hb(){var b=
this.Ob,a=this.oa,c=this.ha(),d=-1===this.Ua?this.La:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Za,orient:this.Ya,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Oa(),playbackRate:this.ma,uid:this.ra,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Va,resumePosition:this.rc(),pan:f,stereoPan:this.fa?
this.$c:null}}Bc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Fa());Mb(this,b.isMuted)}};"use strict";
self.ne=class extends self.kd{constructor(b,a,c){super(b,a,c);this.P.Bb.connect(this.G);this.P.onended=()=>this.Dc()}j(){this.Ca();this.P.Bb.disconnect();super.j()}W(){return this.P.W()}Dc(){this.I=!0;this.ra=-1;Kb(this.u,"ended",this.oa,this.Ob)}O(){return this.W().ended}mc(){return this.I?!0:this.O()}Oa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.ib()}' to position '${c}': `,e)}this.u.Da(d);this.K=this.I=!1;this.Y=b;this.ma=1}Ca(){const b=this.W();b.paused||b.pause();this.u.Pa(b);this.I=!0;this.K=!1;this.ra=-1}kb(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Pa(b);this.K=!0}}Ib(){!this.K||this.I||this.O()||(this.u.Da(this.W()),this.K=!1)}Nb(){this.W().muted=this.Va||this.Hb()}uc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Fa(){let b=this.ma;this.Uc&&(b*=this.u.ic);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}tc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}rc(){return this.Oa()}vc(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.u.Da(this.W()),this.ua=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.mb=null}
self.pe=class extends self.kd{constructor(b,a,c){super(b,a,c);this.o=null;this.$b=d=>this.Dc(d);this.Pc=!0;this.mb=null;this.S=this.bc=this.dc=0;this.Yc=1}j(){this.Ca();V(this);this.$b=null;super.j()}Dc(b){this.K||this.ua||b.target!==this.mb||(this.I=this.Pc=!0,this.ra=-1,V(this),Kb(this.u,"ended",this.oa,this.Ob))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Pc}mc(){return!this.o||this.I?!0:this.O()}Oa(){let b;b=this.K?this.S:this.bc+(U(this)-this.dc)*this.ma;this.Y||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Yc=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.ja;this.o.connect(this.G);this.mb=this.o;this.o.onended=this.$b;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Pc=!1;this.Y=b;this.ma=1;this.dc=U(this);this.bc=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.ra=-1}kb(){this.K||this.I||this.O()||(this.S=this.Oa(),this.Y&&(this.S%=this.ha()),this.K=!0,this.o.stop(0))}Ib(){!this.K||this.I||this.O()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.mb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,T(this,this.La),this.Fa(),this.o.start(0,this.S),this.dc=U(this),this.bc=this.S,this.K=!1)}qc(){return super.qc()*this.Yc}Nb(){this.Yc=this.Va||this.Hb()?0:1;T(this,this.La)}uc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Fa(){let b=this.ma;this.Uc&&(b*=this.u.ic);this.o&&(this.o.playbackRate.value=b)}tc(b){this.I||this.O()||(this.K?this.S=b:(this.kb(),this.S=
b,this.Ib()))}rc(){return this.S}vc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Oa(),this.Y&&(this.S%=this.ha()),this.o.stop(0)):this.ua=!1:this.ua&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.ja,this.o.connect(this.G),this.mb=this.o,this.o.onended=this.$b,this.o.loop=this.Y,T(this,this.La),this.Fa(),this.o.start(0,this.S),this.dc=U(this),this.bc=this.S,this.ua=!1)}Bc(b){super.Bc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Kd=-1;this.T=this.ad="";this.m=null}j(){this.g=null}N(){}U(){}hb(){return{type:this.T,tag:this.ad,params:this.m}}}
self.fe=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.A=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.de=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.yb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.qb=W(this);this.qb.gain.value=c;this.A.connect(this.yb);this.A.connect(this.h);this.yb.connect(this.i);this.yb.connect(this.X);this.X.connect(this.qb);this.qb.connect(this.yb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.yb.disconnect();
this.X.disconnect();this.qb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.gb.nd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.qb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.ce=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Bd=this.Ad="";this.A=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.pb=this.g.createConvolver();this.pb.normalize=c;this.pb.buffer=a;this.A.connect(this.pb);this.A.connect(this.h);this.pb.connect(this.i)}j(){this.A.disconnect();this.pb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}hb(){const b=super.hb();b.bufferOriginalUrl=this.Ad;b.bufferUrl="";b.bufferType=this.Bd;return b}};
self.ge=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.A=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.sb=W(this);this.sb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.sb);this.sb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.sb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.sb.gain,a/100,c,d)}}};
self.ie=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.A=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.A.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.he=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.gb.nd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ke=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.le=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.je=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.A=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Db=W(this);this.Db.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Db.gain);this.B.start(0);this.A.connect(this.Db);this.A.connect(this.h);this.Db.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Db.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ee=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.A=W(this);this.fc=W(this);this.ec=W(this);b=d;.01>b&&(b=.01);this.fc.gain.value=b;this.ec.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.jc=this.g.createWaveShaper();this.Jc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Jc[32768+e]=f,this.Jc[32768-
e-1]=-f;this.jc.curve=this.Jc;this.A.connect(this.fc);this.A.connect(this.h);this.fc.connect(this.jc);this.jc.connect(this.ec);this.ec.connect(this.i)}j(){this.A.disconnect();this.fc.disconnect();this.jc.disconnect();this.ec.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.be=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ae=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Hd=new Float32Array(this.l.frequencyBinCount);this.Vd=new Uint8Array(a);this.Td=this.$a=0;b=this.u;b.Sa.add(this);S(b)}j(){this.u.Sa.delete(this);this.l.disconnect();super.j()}Qa(){this.l.getFloatFrequencyData(this.Hd);this.l.getByteTimeDomainData(this.Vd);const b=this.l.fftSize;let a=this.$a=0;for(var c=0;c<b;++c){let d=(this.Vd[c]-
128)/128;0>d&&(d=-d);this.$a<d&&(this.$a=d);a+=d*d}c=self.gb.xe;this.$a=c(this.$a);this.Td=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Qb(){}function Rb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Sb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.pa.Ma(class extends self.Na{constructor(b){super(b,"browser");this.v="";t(this,[["get-initial-state",a=>this.Ec(a)],["ready-for-sw-messages",()=>Rb(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Fc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Sb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.s.wa()?window.open(c,"_blank"):this.sf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.s.wa()||"macos-wkwebview"===this.v)self.pa.Mb(!0),this.s.Ea({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Qb)}}],["exit-fullscreen",
()=>{if(this.s.wa()||"macos-wkwebview"===this.v)self.pa.Mb(!1),this.s.Ea({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Qb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=
a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Ec(b){this.v=b.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,
screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Cc(b){alert(b.message)}Fc(b){b=b.isFocus;if("nwjs"===this.v){const a="nwjs"===this.v?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";function Tb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Ub(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}
function Vb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Wb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Xb(b){if(!b.Ja)try{b.Ja=await navigator.wakeLock.request("screen"),b.Ja.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ja=null;k(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),k(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),k(b,"wake-lock-error")}}
async function Yb(b){const a=await Zb();k(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Zb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Tb(b),Ub(b),Vb(b),Wb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.pa.Ma(class extends self.Na{constructor(b){super(b,"platform-info");t(this,[["get-initial-state",()=>this.Ec()],["request-wake-lock",()=>Xb(this)],["release-wake-lock",()=>{this.Ja&&(this.Ja.release(),this.Ja=null)}]]);window.addEventListener("resize",()=>Yb(this));this.Ja=null}async Ec(){const b=await Zb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});"use strict";async function $b(b,a){a=a.type;let c=!0;0===a?c=await ac():1===a&&(c=await bc());k(b,"permission-result",{type:a,result:c})}async function ac(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function bc(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.Ma(class extends self.Na{constructor(b){super(b,"touch");n(this,"request-permission",a=>$b(this,a))}});"use strict";function Z(b){b.stopPropagation()}
self.pa.Ma(class extends self.re{constructor(b){super(b)}md(b,a){const c=document.createElement("progress");c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("click",()=>{var d;d||(d={});d.elementId=b;l(this,"click",d)});a.id&&(c.id=
a.id);a.className&&(c.className=a.className);this.wc(c,a);return c}wc(b,a){b.title=a.title;const c=a.value;a=a.max;0<a&&0<=c?(b.max=a,b.value=c):(b.removeAttribute("value"),b.removeAttribute("max"))}});
